### PR TITLE
Auto-Fixing Dataset With Two Levels

### PR DESCRIPTION
**Pull request by vedin-eta**
Added autofix capabilities. Users can use the "--auto-fix" or "-af" argument to auto-fix simple issues such as number of images or size in bytes inside dataset_infos.json. For fixes such as deleting images or changing the coco annotation files, the user is prompted to confirm each time. The user can also use "--yes" or "-y" argument to automatically agree with this prompts when running the command.

Closes https://etacompute.atlassian.net/browse/BOOM-1291.

### CODE REVIEW

**Comment by vedin-eta** [comment]
There seems to be a strange issue with the tests. @jeremi-eta can you check? I tested locally and all passed.

**Comment by jeremi-eta** [comment]
Hey, the test's here are not working really. I did have time to set them up so they pretty much fail by default. No worries though. The "local tests" are the good ones

**Comment by vedin-eta** [comment]
> Hey, the test's here are not working really. I did have time to set them up so they pretty much fail by default. No worries though. The "local tests" are the good ones

Sounds good. This is ready for review, whenever you're ready

**Comment by jeremi-eta** [comment]
@vedin-eta I fixed the tests (on windows they fail, but that requires more work - I think not urgent atm).

You can run tests locally using `tox` command. Check https://github.com/Eta-Compute/AptosConnector/blob/main/README.md#running-tests on how to set it up

**Comment by jeremi-eta** [comment]
@vedin-eta any plans to finish this one up?

**Review by jeremi-eta — APPROVED** [review]
Looks great. I tested locally and it fixed my warning messages. Thanks!

**Pull request merged**
